### ISSUE TITLE
BikeTag Platform Architecture

### ISSUE THREAD

**Issue by KenEucker** [KenEucker/biketag-vue#10]
Here's a quick sketch on paper outlining the relationship between projects on GitHub and how they are abstracted from the user experience:

![PXL_20210402_150417935](https://user-images.githubusercontent.com/1720267/113427637-3f32dd00-938a-11eb-8baf-4649607017b9.jpg)

To explain it in better detail:

### Games

Portland, Phoenix, Seattle, Rome, Vienna, Denver

- Game clients are hosted on biketag.org and the website for the landing page at biketag.org is defined in the templates on the [BikeTag-Website](https://github.com/keneucker/biketag-website) project.
- Game clients in the future will be built using this project, the BikeTag-Vue project, but still hosted from the biketag.org website*.
- Game clients use the Imgur API to create a "new round", which is later picked up by the [BikeTag-App](https://github.com/keneucker/biketag-app) project. 
- * note: during our soft launch, the [BikeTag-Vue](https://github.com/keneucker/biketag-vue) compiled game clients will be hosted from biketag.app.

### Apps

- The current BikeTag "App" is the biketag.org website, built and hosted from the code in the [BikeTag-Website](https://github.com/keneucker/biketag-website) project.
- The next BikeTag "App" will be this project, the [BikeTag-Vue](https://github.com/keneucker/biketag-vue) project.
- The application that is the game of BikeTag, and the code that makes the magic happen, is a nodejs server housed in the [BikeTag-App](https://github.com/keneucker/biketag-app) project. This code runs functions for the RedditBot, authentication with Imgur and Google, and will handle the creation of new BikeTag data in the sanity.io dataset.
- At the onset of BikeTag v3, the [BikeTag-App](https://github.com/keneucker/biketag-app) project will be a serverless function that runs the magic upon request via the BikeTag API.

### API

- The [BikeTag-Api](https://github.com/keneucker/biketag-api) project is new and will be the public javascript client for the BikeTag game. 
- The BikeTag API will be configured with a [BikeTag-App](https://github.com/keneucker/biketag-app) endpoint and Imgur credentials.
- The [BikeTag-Vue](https://github.com/keneucker/biketag-vue) project will start out using this new API.
- The [BikeTag-Website](https://github.com/keneucker/biketag-website) projects will migrate to using the new API after the soft launch of the [BikeTag-Vue](https://github.com/keneucker/biketag-vue) App.
- The BikeTag API will contain logic that will allow anyone to play the game of BikeTag using this API and proper server credentials.

### ImageStore

- Currently, we use Imgur exclusively as our ImageStore and hiding data in the title and description metadata fields using a schema.
- The developed schema above comes from domain knowledge and discovery of all BikeTag games and their nuances and is crucial in providing legacy support.
- We will continue to use Imgur, indefinitely, for displaying images in the BikeTag App. The CDN and reliability of Imgur far exceed our abilities and they provide unlimited high-resolution uploads. 
- The [BikeTag-Vue](https://github.com/keneucker/biketag-vue) project will get its data from a DataStore, sanity.io not Imgur, that will provide the Imgur links for a given game's images.
- Sanity.IO also provides an ImageStore alongside the Data, on a free tier, so images will be backed up on Sanity.io and used if Imgur goes down.
- When Imgur availability fails, the BikeTag API should recognize this and replace the given Imgur URLs with the URLs of the redundant images stored in sanity.io.

### DataStore

- Currently, our data is stored within the Imgur images.
- For the [BikeTag-Vue](https://github.com/keneucker/biketag-vue) project and the new BikeTag API, data will come from sanity.io and the URLs for images will come from that datastore as well.
- The datastore is not something that will be querying sanity.io regularly. Sanity is for compiling the app itself and injecting the required data into the app.
- The BikeTag API does not modify the DataStore -- only provides a mechanism for creating new BikeTag images and sending them to the correct Imgur album while interacting with a BikeTag App server (or serverless function).
- The DataStore is managed both within the sanity studio provided, the project for the studio and sanity data is the [BikeTag-Sanity](https://github.com/keneucker/biketag-sanity) project.
- The DataStore can be modified and added to by the BikeTag App server for the magic parts.

**Comment by ItsOkayItsOfficial** [comment]
Added this information to the repo wiki under [Bike Tag Architecture](https://github.com/KenEucker/biketag-vue/wiki/Bike-Tag-Architecture) so we can keep Issues decluttered.
