### ISSUE TITLE
[BUG] Long hints don't fit in the text area

### ISSUE THREAD

**Issue by SievaFliesAlone** [KenEucker/biketag-vue#124]
**Describe the bug**
Long tag hints (>~25 characters) don't fit hint text area

**To Reproduce**
1. Go to the home screen
2. Under the mysteey photo, press “Hint” button

**Expected behavior**
Text fits the area

**Screenshots**
![Screenshot_20220315-072107_Fennec](https://user-images.githubusercontent.com/790717/158399583-b7201c52-1898-40d9-80a8-f49621acc511.png)

**Environment (please complete the following information):**
Firefox 98 on Android

**Comment by ykyu** [comment]
Easy fix would be to add the following to Home.css:

```
.biketag-label p { margin: 0.35rem 0 0 0; }
.biketag-label { background-image: none !important; border: 4px solid #000000; background-color: #ffffff; }
```

This just gets rid of the image background, which can't account for variable height of hints. Thick black border still matches the style okay, imo.

**Comment by KenEucker** [comment]
For this issue, we will be implementing the popover from the design. We just didn't get that into the app before our release.

![image](https://user-images.githubusercontent.com/1720267/158898881-126c9fac-c1c5-4388-a9cd-82d6dc058de9.png)

**Comment by KenEucker** [comment]
RE: hints
https://www.sliderrevolution.com/design/cool-javascript-animations/

**Comment by KenEucker** [comment]
The hint popover has been added:

![Screen Shot 2022-03-22 at 2 19 45 PM](https://user-images.githubusercontent.com/1720267/159577908-24c209de-cd3c-4523-a334-e74f52b7f34f.png)

**Comment by SievaFliesAlone** [comment]
Ohh it looks so cool! Thank you!
