### ISSUE TITLE
Move Top-10, Cities, Players links to a less distracting area

### ISSUE THREAD

**Issue by SievaFliesAlone** [KenEucker/biketag-vue#125]
While cool, links on the floating banner (Top-10, Cities, Players) are not that relevant to the playing process to be on top all the time. Previously, the old app didn't have 2 of them at all, while “Worldwide” was on the bottom of the page, and that wasn't an issue. Now, they are distracting.

I would move them to the hamburger menu.

![Screenshot_20220315-074232_Fennec](https://user-images.githubusercontent.com/790717/158403138-4afd629f-02a2-4de6-b4cc-84649c73946e.png)

**Comment by KenEucker** [comment]
@anibyl I'll let you close your own issue here.

This has been resolved.

**Comment by SievaFliesAlone** [comment]
Thank you!
