### ISSUE TITLE
Create `Screens` entry to repo Wiki

### ISSUE THREAD

**Issue by ItsOkayItsOfficial** [KenEucker/biketag-vue#15]
Create and populate a `Screens` entry for the repo Wiki that includes a title, definition, and use-case for each of the screens (and components?) in the biketag-vue app.

**Comment by KenEucker** [comment]
The wiki page has been created, and I linked to the app I used to make the wireframes that we can use or not use. Still need to add the use cases to that wiki document.

https://github.com/KenEucker/biketag-vue/wiki/Screens
