### ISSUE TITLE
The provided trial url (client.org) doesn't work

### ISSUE THREAD

**Issue by ammaratef45** [KenEucker/biketag-vue#177]
Is client.org the correct URL?

https://github.com/KenEucker/biketag-vue/blob/27f5d6914b8ba56a9996bf5b15a9fddb866ad074/README.md?plain=1#L85

**Comment by KenEucker** [comment]
@ammaratef45 there seems to be a mistake in the documentation. 

There is no "trial". The live site is at https://biketag.org

**Comment by ammaratef45** [comment]
Cool, thanks for confirming
