### ISSUE TITLE
[BUG] Unable to run locally

### ISSUE THREAD

**Issue by ammaratef45** [KenEucker/biketag-vue#178]
**Describe the bug**
When I run using `yarn run dev` I see a blank page at `http://localhost:8080/#/`

The error in the console is the following:
```
Uncaught TypeError: Cannot destructure property 'isAuthenticated' of 'useAuth0(...)' as it is undefined.
    at setup (App.vue:44:9)
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:18)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7290:25)
    at setupComponent (runtime-core.esm-bundler.js:7251:36)
    at mountComponent (runtime-core.esm-bundler.js:5647:7)
    at processComponent (runtime-core.esm-bundler.js:5613:9)
    at patch (runtime-core.esm-bundler.js:5088:11)
    at render2 (runtime-core.esm-bundler.js:6380:7)
    at mount (runtime-core.esm-bundler.js:3832:13)
    at app.mount (runtime-dom.esm-bundler.js:1449:19)
```

**To Reproduce**
1. Clone the repo.
2. `yarn install`
3. `yarn run dev`

**Expected behavior**
A functional website.

**Screenshots**
N/A.

**Environment (please complete the following information):**
 - Library version [e.g. 1.0.0]: not sure which library is meant here, but the yarn version is `1.22.19`
 - OS [e.g. macOS]: macOs
 - NodeJS version [e.g.14.16.0]: `v18.17.1`

**Additional context**
N/A.

**Comment by KenEucker** [comment]
@ammaratef45 
Use the `develop` branch. Production is a bit behind.

**Comment by KenEucker** [comment]
Also, @ammaratef45 , all feedback you can provide about your experience setting things up for the first time are greatly appreciated.

If you can suggest improvements to the documentation or configuration, I'm all for it.

Thanks!

**Comment by KenEucker** [comment]
@ammaratef45 pull in the recent changes to `develop` and it should be fixed. There are environment variables you'll want to set if you're hoping to target a specific game.

**Comment by KenEucker** [comment]
@ammaratef45 please let me know if you have any further issues. I am closing this issue for now as recent updates to `develop` have been proven to work for new people collaborating on the project.

**Comment by ammaratef45** [comment]
@KenEucker I've tried the `deveolop` branch and it worked

I will update you on my experience ramping up, I have no experience with vue so I'm figuring it out as I go, thanks for being responsive and for the great work
