### ISSUE TITLE
Add VueMaterial

### ISSUE THREAD

**Issue by KenEucker** [KenEucker/biketag-vue#18]
Add VueMaterial to the project for rich components that we don't have to write by hand.

https://vuematerial.io/

**Comment by KenEucker** [comment]
For the app menu: https://vuematerial.io/components/bottom-bar

For the queue: https://vuematerial.io/components/steppers

For each individual tag: https://vuematerial.io/components/card

For bicons: https://vuematerial.io/components/avatar


Misc:
https://vuematerial.io/components/progress-spinner
https://vuematerial.io/components/speed-dial

**Comment by ItsOkayItsOfficial** [comment]
`vue-material` added to branch `scaffold-0.9-ts`

**Comment by KenEucker** [comment]
Reopening due to shifting away from vuematerial due to lack of vue3 support.

**Comment by KenEucker** [comment]
I've begun implementing PrimeVue:
https://primefaces.org/primevue/

With these components top of mind:
https://primefaces.org/primevue/showcase/#/timeline
https://primefaces.org/primevue/showcase/#/card
https://primefaces.org/primevue/showcase/#/splitter
https://primefaces.org/primevue/showcase/#/fileupload
https://primefaces.org/primevue/showcase/#/steps
https://primefaces.org/primevue/showcase/#/message
https://primefaces.org/primevue/showcase/#/carousel
https://primefaces.org/primevue/showcase/#/galleria/advanced
https://primefaces.org/primevue/showcase/#/galleria/thumbnail
https://primefaces.org/primevue/showcase/#/avatar
https://primefaces.org/primevue/showcase/#/inplace
https://primefaces.org/primevue/showcase/#/skeleton

**Comment by KenEucker** [comment]
PrimeVue has been added to the project.
