### ISSUE TITLE
[BUG] Player's tags don't always display

### ISSUE THREAD

**Issue by najadojo** [KenEucker/biketag-vue#216]
**Describe the bug**
Player's tag page doesn't show tags

**To Reproduce**
1. Open Microsoft Edge or Safari on Mac
2. Open a new InPrivate window
3. Enter site address seattle.biketag.org
4. Wait for page to load and select the hamburger menu, top right 
5. Select Top 10
6. Select u/najadojo

**Expected behavior**
u/najadojo's tag list should display

**Screenshots**
<img width="871" alt="image" src="https://github.com/KenEucker/biketag-vue/assets/17411617/00c644e9-9b1a-44cd-b5c9-9df3e4084a5f">

**Environment (please complete the following information):**
Mac and iPhone, Chrome and Safari browsers, clean cache

**Comment by KenEucker** [comment]
This has been fixed and will go out with the next deploy to production.
