### ISSUE TITLE
Use venomgram as starter for scaffolding

### ISSUE THREAD

**Issue by KenEucker** [KenEucker/biketag-vue#4]
Using source code from this project: https://github.com/ibrahimpg/venomgram-ui

We should be able to get started with a Vue application that has views that will work well with the BikeTag App design and make it easy to follow the wireframe designs without having to do it all from scratch.

**Comment by ItsOkayItsOfficial** [comment]
Scaffolding now exists on the `scaffold-0.9` branch. Moving to complete.
